// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe3Wt43hjJ4j9ImjlO1LLRASMEVI22ScQ',
    appId: '1:433626121111:web:78aa18351d5ea46447bad2',
    messagingSenderId: '433626121111',
    projectId: 'fir-nti-9c0b2',
    authDomain: 'fir-nti-9c0b2.firebaseapp.com',
    storageBucket: 'fir-nti-9c0b2.firebasestorage.app',
    measurementId: 'G-CTH8C5F2BB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMdog_GwJwNTjgtEpJG4j3Oec96BQoDXY',
    appId: '1:433626121111:android:6f73d496eefbd16047bad2',
    messagingSenderId: '433626121111',
    projectId: 'fir-nti-9c0b2',
    storageBucket: 'fir-nti-9c0b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCuAHHknbkrkFmh70Er3fMqYtMpJfmF2Q',
    appId: '1:433626121111:ios:1f03bf90aa14c6a947bad2',
    messagingSenderId: '433626121111',
    projectId: 'fir-nti-9c0b2',
    storageBucket: 'fir-nti-9c0b2.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNti',
  );
}
